### PR TITLE
add confirmation and success components in wire withdrawal page

### PR DESCRIPTION
**Pull request by dhanesh-kapadiya**
Added confirmation block on Wire withdrawal page
Added success block on positive response
Screenshot 2020-06-15 at 6 10 56 AM
Screenshot 2020-06-15 at 6 12 16 AM
Screenshot 2020-06-15 at 6 13 03 AM

### CODE REVIEW

**Comment by markusait** [comment]
Convince me of the opposite but I think Stably purple is better than green

**Comment by dhanesh-kapadiya** [comment]
> Convince me of the opposite but I think Stably purple is better than green

I made that with purple color initially, but then it got tooo much purple in the whole page, so changed it to green. If we get confirmation from others as well I can change it back to stably purple.

**Comment by dhanesh-kapadiya** [comment]
> > Convince me of the opposite but I think Stably purple is better than green
> 
> I made that with purple color initially, but then it got tooo much purple in the whole page, so changed it to green. If we get confirmation from others as well I can change it back to stably purple.

Screenshot 2020-06-15 at 7 08 47 AM
This is how it looks like.

**Comment by dhanesh-kapadiya** [comment]
> LGTM.
> I also have 2 comments:
> 
> * I think those component sizes should be smaller to have a good fit its contents
> * In success page, contents are not vertical centered align

I'll update the size again. and make it vertically centred.

**Comment by Git-on-my-level** [comment]
What about purple outline and white fill?

Also I think confirmation and success should be on separate "pages", I don't think creating modals is consistent with our UX

Agree that the boxes for content is too big, should probably just fit the content with some extra space instead of being the same size.

I think better fitting boxes on their own "page" would be better, but let me know if you disagree

**Comment by dhanesh-kapadiya** [comment]
> What about purple outline and white fill?
> 
> Also I think confirmation and success should be on separate "pages", I don't think creating modals is consistent with our UX
> 
> Agree that the boxes for content is too big, should probably just fit the content with some extra space instead of being the same size.
> 
> I think better fitting boxes on their own "page" would be better, but let me know if you disagree

If we add pages instead of just components, users will be able to navigate to those pages using url without any data and if a user access the confirmation page without the data being passed to the page, it will be a really bad UX unless we pass the data in url params and to prevent the use to access these pages directly we have to forcefully redirect them to home page.

IMO these two components only serve static data. It will be a good approach if we keep these components inside the transfer page as modal instead of standalone pages.
LMK what you suggest.

**Comment by dhanesh-kapadiya** [comment]
Changed UI for confirm and success blocks.

Screenshot 2020-06-17 at 6 09 56 AM

Screenshot 2020-06-17 at 6 07 26 AM

@Git-on-my-level should I change the block to pages? I have given my reasons in a comment above

**Pull request merged**
