### PR TITLE
added 2fa validation for kgld and removed bank acc from acc setting page

### PR DESCRIPTION
**Pull request by chauhannishith**
[demo link](http://stably-nishithchauhan-frontend-share.s3-website-us-west-2.amazonaws.com/account)
image

### CODE REVIEW

**Comment by Git-on-my-level** [comment]
Generally looks fine but should we call it TwoFA when we already have MFA? Could be confusing later on or is there actually a reason to differentiate?

**Comment by chauhannishith** [comment]
@Git-on-my-level  should this PR be merged and fix disabling MFA later in a separate PR?

**Comment by Git-on-my-level** [comment]
> @Git-on-my-level should this PR be merged and fix disabling MFA later in a separate PR?

I'll let you decide, if this blocks other things that should be worked on then yes, otherwise you can leave this open and look for a fix or ask someone else to take a stab at it

**Comment by chauhannishith** [comment]
merging this for now in order to work on the bank account page

**Pull request merged**
